language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"

matrix:
  allow_failures:
    - perl: "5.20"

notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
  irc: "irc.perl.org#metacpan-travis"


env:
  global:
    # We use a non-standard port to avoid trashing production
    # but travis will have it running on the standard port.
    - ES=localhost:9200
    # Carton --deployment only works on the same version of perl
    # that the snapshot was built from.
    - DEPLOYMENT_PERL_VERSION=5.18


before_install:
  - sudo service elasticsearch restart
  - pwd

  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n Carton
  - sudo apt-get install libgmp-dev

  # Carton refuses to update Safe.pm to the version specified in the cpanfile and the
  # version that's core in 5.16 is too old (it fails to work with Devel::Cover).
  - cpanm -n Safe@2.35

install:
  - 'carton install `test "${TRAVIS_PERL_VERSION}" = "${DEPLOYMENT_PERL_VERSION}" && echo " --deployment"`'

before_script:
  - "perl -i -pe 's/(servers :)9900/localhost:9200/' metacpan_server_testing.conf"

script:
  # Devel::Cover isn't in the cpanfile
  # but if it's installed into the global dirs this should work.
  # NOTE: No '-r' for prove; 't/fakecpan.t' does the recursion for us.
  - HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,local carton exec prove -lv t

after_success:
  - cover -report coveralls

after_script:
  - cat ~/.cpanm/build.log

services:
  - elasticsearch
